- name: Install a list of packages
  apt:
    pkg:
    - fzf
    - python3
    - python3-setuptools
    - python3-pip
    - libpango1.0-0
    - libpangox-1.0-0
    - python3-gpg
    - httpie
    - aptitude
    - snapd
    - apt-transport-https
    - nodejs 
    - npm
    - libx11-dev
    - libxext-dev
    - gimp
    - inkscape
    - vlc
    - kolourpaint
    - meld
    - planner
    - freeplane
    - git-flow
    - obs-studio 
    - obs-plugins 
    - obs-build
    - htop

- npm:
    name: yarn
    global: yes


- npm:
    name: neovim
    global: yes

- pip:
    name: 
    - ueberzug
    - pynvim

- name: Workspace tasks
  import_tasks: workspace.yml

- name: Docker tasks
  import_tasks: docker.yml

- name: ZSH tasks
  import_tasks: zsh.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: NVim
  import_tasks: nvim.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: Zoom tasks
  import_tasks: zoom.yml

- name: Dropbox tasks
  import_tasks: dropbox.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: Install via snap (Classic)
  snap:
    name: 
      - code
    classic: yes

- name: Install via snap
  snap:
    name: 
      - drawio

#should have
# ansible-playbook  --ask-become-pass site.yml
