---
- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - fzf
    - python3
    - python3-setuptools
    - python3-pip
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - libpango1.0-0
    - libpangox-1.0-0
    - python3-gpg
    - httpie
    - aptitude
    - snapd
    - apt-transport-https
    
- name: Install via snap
  snap:
    name: code
    classic: yes

- name: Install via snap
  snap:
    name: microk8s
    classic: yes

- name: Adding user {{ lookup('env', 'USER') }} to groups
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
    groups: microk8s
    append: yes   
    
- name: HELM - Add an Apt signing key for
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    
- name: HELM - Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present    
    
- name: HELM - Update repositories cache and install "helm" package
  apt:
    name: helm
    update_cache: yes

     
#    sudo usermod -a -G microk8s yehuda
#    sudo chown -f -R yehuda ~/.kube

# veracrypt

#should have
# ansible-playbook  --ask-become-pass site.yml
#
#
# Todo:
# nix

