- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - fzf
    - python3
    - python3-setuptools
    - python3-pip
    - libpango1.0-0
    - libpangox-1.0-0
    - python3-gpg
    - httpie
    - aptitude
    - snapd
    - apt-transport-https

- name: Workspace tasks
  import_tasks: workspace.yml

- name: Docker tasks
  import_tasks: docker.yml

- name: ZSH tasks
  import_tasks: zsh.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: Zoom tasks
  import_tasks: zoom.yml

- name: Dropbox tasks
  import_tasks: dropbox.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: Install via snap
  snap:
    name: 
      - code
    classic: yes

# zsh theme
#    sudo usermod -a -G microk8s yehuda
#    sudo chown -f -R yehuda ~/.kube
#       sudo vi /etc/locale.gen
#       https://wiki.debian.org/Locale
#       locale-gen 
# veracrypt

#should have
# ansible-playbook  --ask-become-pass site.yml
#
#
# Todo:
# nix
# sudo usermod -aG docker yehuda

