---
- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - aria2
    - fzf
    - python3
    - python3-setuptools
    - python3-pip
    - firmware-iwlwifi
    - rsync
    - helm
    - snapd               # might require updates
