- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - fzf
    - python3
    - python3-setuptools
    - python3-pip
    - libpango1.0-0
    - libpangox-1.0-0
    - python3-gpg
    - httpie
    - aptitude
    - snapd
    - apt-transport-https
    - docker 
    - docker-compose

- name: Include ZSH tasks
  import_tasks: zsh.yml
  become: yes
  become_user: "{{ lookup('env','USER') }}"

- name: Install via snap
  snap:
    name: 
      - code
    classic: yes

#- name: Adding user {{ lookup('env', 'USER') }} to groups
#  user:
#    name: "{{ lookup('env', 'USER') }}"
#    shell: /bin/zsh
#    groups: microk8s
#    append: yes   
    
- name: HELM - Add an Apt signing key for
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    
- name: HELM - Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present    
    
- name: HELM - Update repositories cache and install "helm" package
  apt:
    name: helm
    update_cache: yes

# zsh theme
#    sudo usermod -a -G microk8s yehuda
#    sudo chown -f -R yehuda ~/.kube
#       sudo vi /etc/locale.gen
#       https://wiki.debian.org/Locale
#       locale-gen 
# veracrypt

#should have
# ansible-playbook  --ask-become-pass site.yml
#
#
# Todo:
# nix
# sudo usermod -aG docker yehuda

