- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - python3-pynvim
    - virtualenv
  become: yes
  become_user: root

- pip:
    name:
      - ueberzug

- name: nvim workspace
  file:
    path: "{{ lookup('env','HOME') }}/{{ item }}"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: u+rwx
    state: directory  
  loop:
    - .local/share/nvim/site/autoload/
    - .config/nvim
    - Data/python/v2.7

- name: check venv-global
  stat:
    path: "{{ lookup('env','HOME') }}/Data/python/v2.7/venv-global"
  register: venv_global_f_r

- name: "Create venv-global"
  command: virtualenv -p /usr/bin/python2.7 {{ lookup('env','HOME') }}/Data/python/v2.7/venv-global
  when: not venv_global_f_r.stat.exists


- name: check neovim venv-global
  stat:
    path: "{{ lookup('env','HOME') }}/Data/python/v2.7/venv-global/lib/python2.7/site-packages/neovim"
  register: neovim_venv_global_f_r

- name: install neovim package
  command: "{{ lookup('env','HOME') }}/Data/python/v2.7/venv-global/bin/python -m pip install neovim"
  when: not neovim_venv_global_f_r.stat.exists

- name: Download oh-my-zsh
  get_url:
    url:   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload/plug.vim"
    # init.vim moved to lined files .../config-files/home/.config/nvim
    #- name: Write init.vim
    #  template:
    #      src: h.config.nvim.init.vim.j2
    #      dest: "{{ lookup('env','HOME') }}/.config/nvim/init.vim"
    #      mode: u+rw
