- name: Install a list of packages
  apt:
    pkg:
    - neovim 
    - neovim-qt
    - python3-pynvim
  become: yes
  become_user: root

- pip:
    name:
      - ueberzug

- name: nvim workspace
  file:
    path: "{{ lookup('env','HOME') }}/{{ item }}"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: u+rwx
    state: directory  
  loop:
    - .local/share/nvim/site/autoload/
    - .config/nvim

- name: Download oh-my-zsh
  get_url:
    url:   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload/plug.vim"

- name: Write init.vim
  template:
      src: h.config.nvim.init.vim.j2
      dest: "{{ lookup('env','HOME') }}/.config/nvim/init.vim"
      mode: u+rw
